version: 2.1
orbs:
  circleci-cli: circleci/circleci-cli@0.1.9
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-


      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # we need to install CircleCI CLI tool
      # to run the "manual" tests
      - circleci-cli/install
      - run: npm install --save-dev browserstack-cypress-cli
      - run: npx browserstack-cypress --username mayankmaurya4 --key JzJJjes3cyzHaynTqJpe run --sync
workflows:
  orb_tests:
    jobs:
    - build